### ISSUE TITLE
Automated API documentation

### ISSUE THREAD

**Issue by morremeyer** [envelope-zero/backend#107]
**Is your feature request related to a problem? Please describe.**

We need API documentation.

**Describe the solution you'd like**

`/docs` endpoint that has API documentation.

**Describe alternatives you've considered**
_None_

**Additional context**
_None_

**TODO**

* [x] Add general swagger configuration (#116)
* [x] Split GetBudget and GetEnvelope into two functions for the default and month endpoints (#132)
* [x] Add documentation for all API endpoints (#124)
* [x] Only use structs for response bodies so that they can be added correctly to the documentation (#124)
