### ISSUE TITLE
Allocation setting shortcuts

### ISSUE THREAD

**Issue by morremeyer** [envelope-zero/backend#44]
There need to be API endpoints with actions to set envelope allocations for all envelopes to:

* [ ] the allocations of the month before #303 
* [ ] the spend of the month before #303 
* [x] ~the average spend of the year before~ moved to #294.
* [x] set all allocations to 0 #296
